### ISSUE TITLE
商店版圈x访问BoxJS只显示boxjs字样，清除备份、清除订阅脚本都运行了都无效

### ISSUE THREAD

**Issue by HweeJohn** [ipuppet/BoxJsHelper#1]
日志显示TypeError: null is not an object (evaluating 'delete bak.bak')

**Comment by ipuppet** [comment]
换tf的脚本 用.net试试

**Comment by HweeJohn** [comment]
> 换tf的脚本 用.net试试

最开始用的tf，回来换商店版的试了，就是我用loon备份文件来恢复圈x的了

**Comment by ipuppet** [comment]
> > 换tf的脚本 用.net试试
> 
> 
> 
> 最开始用的tf，回来换商店版的试了，就是我用loon备份文件来恢复圈x的了

理论上loon能用那么其他软件也能用，本脚本可以理解成一个浏览器，只是附带了些快捷功能。
可加群[https://t.me/PinTG](https://t.me/PinTG) @sk_kaguya
